[theme]
name = "gruvbox-dark"
[icons]
name = "awesome6"

[[block]]
block = "speedtest"
interval = 60
format = "{ping}{speed_down:4*B}{speed_up:4*B}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
format = "%Y-%m-%d %R"
timezone = "Asia/Shanghai"
interval = 40
locale = "zh_CN"

[[block]]
block = "custom"
command = "echo  $(uname -r | tr - . | cut -d. -f1-3)"
#state="Idle"
interval = "once"
